### ISSUE TITLE
Creating Project Div Size Adjustment

### ISSUE THREAD

**Issue by jerryiscat** [hcp-uw/societas#44]
In the creating project page(http://localhost:5173/account/create), we can't see the bottom lines. When I make the screen text smaller, I can see those bottom lines. It may be related the css style of the div.
<img width="1301" alt="Screen Shot 2023-12-05 at 6 19 52 PM" src="https://github.com/hcp-uw/societas/assets/94934251/dd357808-7f97-4f65-9ced-290f2b26b885">

**Comment by SantiagoG14** [comment]
In the latest pull request, this bug was fixed. All of the work is in App.tsx, it had to do with heights of both the nav and head main element not being set properly.
